"""add scores to matches

Revision ID: 3c6eef954444
Revises: a5384723802e
Create Date: 2026-10-04 13:29:40.080083

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c6eef954444"
down_revision: str | Sequence[str] | None = "a5384723802e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column(
            "home_score", sa.String(length=16), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "matches",
        sa.Column(
            "away_score", sa.String(length=16), server_default="0", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "away_score")
    op.drop_column("matches", "home_score")
    # ### end Alembic commands ###
