"""add status to matches

Revision ID: a5384723802e
Revises: 76eeec0d2b59
Create Date: 2026-10-03 21:30:23.096806

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5384723802e"
down_revision: str | Sequence[str] | None = "76eeec0d2b59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column("status", sa.String(length=8), server_default="pre", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("matches", "status")
    # ### end Alembic commands ###
